name: Build Windows iso
on:
  workflow_call:
    inputs:
    UUPUrl:
      description: 'UUP script download url'
      required: true
    UUPScript:
      description: 'UUP script'
      required: true
      default: 'uupdump.net'

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: C:\uup
    steps:
    - name: Installation dependencies
      working-directory: .\
      run: |
        choco install --yes --no-progress curl rclone
        mkdir -p C:\uup
    - name: uupdump.net UUP convert to ISO
      if: inputs.UUPScript == 'uupdump.net'
      shell: cmd
      run: |
        curl -L "${{ inputs.UUPUrl }}" -o uup.zip
        unzip -oq uup.zip
        echo 0 | .\uup_download_windows.cmd
    - name: uup.rg-adguard.net UUP convert to ISO
      if: inputs.UUPScript == 'uup.rg-adguard.net'
      run: |
        curl -L "${{ inputs.UUPUrl }}" -o uup.cmd
        echo 0 | .\uup.cmd
    - name: Check the ISO hash
      run: |
        $ISO=Get-ChildItem *.ISO -Name
        Get-FileHash $ISO -Algorithm SHA1| Format-List
        (Get-Item $ISO).Length/1MB
