name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true
      uupapp:
        description: 'uup app (uupdump/uuprg)'
        required: true
        default: 'uupdump'
      Max-Days:
        description: 'upload max days'
        required: true
        default: '14'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Installation dependencies
      run: |
        curl https://curl.se/windows/dl-7.77.0_3/curl-7.77.0_3-win64-mingw.zip -o curl.zip
        unzip -oq curl.zip
        $tmp=Get-ChildItem curl*mingw -Name
        Set-Alias curl $tmp\bin\curl.exe
    - name: uupdump uup convert to iso
      if: github.event.inputs.uupapp == 'uupdump'
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip -oq uup.zip
        echo 0 | .\uup_download_windows.cmd
    - name: uuprg uup convert to iso
      if: github.event.inputs.uupapp == 'uuprg'
      run: |
        $PATH=$(pwd).Path
        mkdir C:\uup
        cd C:\uup
        curl "${{ github.event.inputs.uupurl }}" -o uup.cmd
        echo 0 | .\uup.cmd
        $ISO=Get-ChildItem *.ISO -Name
        Move-Item $ISO $PATH
    - name: test
      if: github.event.inputs.uupapp == 'test'
      run: |
        curl http://sgp-ping.vultr.com/vultr.com.100MB.bin -o test.ISO
    - name: out iso version
      run: |
        $ISO=Get-ChildItem *.ISO -Name
        (Get-Item $ISO).Length/1MB
    - name: upload
      run: |
        $ISO=Get-ChildItem *.ISO -Name
        curl -#T $ISO https://transfer.hx0i.xyz/$ISO -H "Max-Days: ${{ github.event.inputs.Max-Days }}"
