name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip uup.zip
        echo 0 | ./uup_download_linux.sh
    - name: Upload to Google Drive
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        upload-from: ./*.iso
        upload-to: /windows
