name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Installation dependencies
      run: |
        curl https://curl.se/windows/dl-7.77.0_3/curl-7.77.0_3-win64-mingw.zip -o curl.zip
        unzip -oq curl.zip
        $tmp=Get-ChildItem curl*mingw -Name
        Set-Alias curl $tmp\bin\curl.exe
    - name: uup convert to iso
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip -oq uup.zip
        touch dwajinfoaiwnwgiha.ISO
        $PATH=$(pwd).Path
        $ISO=Get-ChildItem *.ISO -Name
        echo "PATH=$PATH" >> $GITHUB_ENV
        echo "ISO=$ISO" >> $GITHUB_ENV
    - name: upload
      run: |
        curl -#T ./${{ env.ISO }} https://transfer.sh/${{ env.ISO }}
