name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install software
      run: |
        sudo apt-get install aria2 cabextract wimtools chntpw genisoimage
    - name: uup convert to iso
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip uup.zip
        echo 0 | sudo bash ./uup_download_linux.sh
    - name: Upload to Google Drive
      uses: satackey/action-google-drive@v1
      with:
        skicka-tokencache-json: ${{ secrets.SKICKA_TOKENCACHE_JSON }}
        upload-from: ./*.iso
        upload-to: /windows

        # For those who set up Google Drive API client ID and secret themselves
        google-client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        google-client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}

