name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true
      uupapp:
        description: 'uup script'
        type: choice
        options:
          - uupdump.net
          - uup.rg-adguard.net
      transfer:
        description: 'transfer domain'
        required: true
        default: 'https://transfer.sh/'
      Max-Days:
        description: 'upload max days'
        required: false
        default: ''

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        working-directory: C:\uup
    steps:
    - name: Installation dependencies
      working-directory: .\
      run: |
        choco install curl
        choco install rclone
        mkdir -p C:\uup
    - name: uupdump uup convert to iso
      if: github.event.inputs.uupapp == 'uupdump.net'
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip -oq uup.zip
        echo 0 | .\uup_download_windows.cmd
    - name: uuprg uup convert to iso
      if: github.event.inputs.uupapp == 'uup.rg-adguard.net'
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.cmd
        echo 0 | .\uup.cmd
    - name: out iso version
      run: |
        $ISO=Get-ChildItem *.ISO -Name
        Get-FileHash $ISO -Algorithm SHA1| Format-List
        (Get-Item $ISO).Length/1MB
    - name: upload to transfer.sh
      run: |
        $ISO=Get-ChildItem *.ISO -Name
        curl -H "Max-Days: ${{ github.event.inputs.Max-Days }}" -sT $ISO ${{ github.event.inputs.transfer }}
    - name: upload to onedrive
      run: |
        mkdir -p $ENV:APPDATA\rclone
        echo '${{ secrets.RCLONE_CONFIG }}' >> $ENV:APPDATA\rclone\rclone.conf
        $ISO=Get-ChildItem *.ISO -Name
        rclone copy $ISO "onedrive:/Public/os/windows" -P
