name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install software
      run: |
        sudo apt-get install aria2 cabextract wimtools chntpw genisoimage
    - name: uup convert to iso
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip uup.zip
        echo 0 | sudo bash ./uup_download_linux.sh
    - name: Upload firmware to WeTransfer
      run: |
        curl -fsSL git.io/file-transfer | sh
        file = $(find *.iso)
        ./transfer wet -s -p 16 --no-progress ${file} 2>&1 | tee wetransfer.log
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
