name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: uup convert to iso
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip uup.zip
        echo 0 | ./uup_download_windows.cmd
        echo "$path=$(pwd).Path" >> $GITHUB_ENV
        echo "$ISO=Get-ChildItem *.ISO -Name" >> $GITHUB_ENV
    - name: upload
      run: |
        curl --upload-file ./{{ env.$ISO }} https://transfer.sh/${{ env.ISO }}
