name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: uup convert to iso
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip -oq uup.zip
        touch dwajinfoaiwnwgiha.ISO
        $path=$(pwd).Path
        $ISO=Get-ChildItem *.ISO -Name
        echo "path=$path" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        echo "ISO=$ISO" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
    - name: upload
      run: |
        curl https://curl.se/windows/dl-7.77.0_3/curl-7.77.0_3-win64-mingw.zip -o curl.zip
        unzip -oq curl.zip
        $tmp=Get-ChildItem curl*mingw -Name
        Set-Alias realcurl $tmp\bin\curl.exe
        realcurl -#T ./${{ env.ISO }} https://transfer.sh/${{ env.ISO }}
