name: Build Windows iso
on:
  workflow_dispatch:
    inputs:
      uupurl:
        description: 'uup script url'
        required: true
      uupapp:
        description: 'uup app (uupdump/uuprg)'
        required: true
        default: 'uupdump'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Installation dependencies
      run: |
        curl https://curl.se/windows/dl-7.77.0_3/curl-7.77.0_3-win64-mingw.zip -o curl.zip
        unzip -oq curl.zip
        $tmp=Get-ChildItem curl*mingw -Name
        Set-Alias curl $tmp\bin\curl.exe
    - name: uup convert to iso
      if: github.event.inputs.uupapp == "uupdump"
      run: |
        curl "${{ github.event.inputs.uupurl }}" -o uup.zip
        unzip -oq uup.zip
        echo 0 | .\uup_download_windows.cmd
    - name: uup convert to iso
      if: github.event.inputs.uupapp == "uuprg"
      run: |
        $PATH=$(pwd).Path
        $ISO=Get-ChildItem *.ISO -Name
        mkdir C:\uup
        cd C:\uup
        curl "${{ github.event.inputs.uupurl }}" -o uup.cmd
        echo 0 | .\uup.cmd
        Move-Item $ISO $PATH
    - name: out iso version
      run: |
        Get-ChildItem *.ISO -Name
    - name: upload
      run: |
        $ISO=Get-ChildItem *.ISO -Name
        curl -#T $ISO https://transfer.sh/$ISO
